// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	student.proto

It has these top-level messages:
	Student
	Response
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Student struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age         int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *Student) Reset()                    { *m = Student{} }
func (m *Student) String() string            { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()               {}
func (*Student) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Student) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Response struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Student)(nil), "main.Student")
	proto.RegisterType((*Response)(nil), "main.Response")
}

func init() { proto.RegisterFile("student.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0xa9, 0xad, 0xb6, 0x3d, 0x11, 0xe4, 0xa6, 0x8c, 0xa1, 0x53, 0x27, 0x17, 0x77, 0xdf,
	0xc1, 0xf8, 0x04, 0x31, 0x3d, 0x24, 0x43, 0x2e, 0xa1, 0x97, 0xbe, 0xbf, 0x34, 0x12, 0x70, 0xfb,
	0xff, 0xef, 0x8e, 0x8f, 0x1f, 0x2e, 0x92, 0xb7, 0x85, 0x38, 0xdf, 0xd2, 0x1a, 0x73, 0xc4, 0x2e,
	0x58, 0xcf, 0xd3, 0x13, 0xfa, 0xd7, 0x0f, 0x23, 0x42, 0xc7, 0x36, 0x90, 0x6a, 0x74, 0x33, 0x8f,
	0xa6, 0x64, 0xbc, 0x42, 0x6b, 0x3f, 0xa4, 0x0e, 0xba, 0x99, 0x8f, 0x66, 0x8f, 0xa8, 0xe1, 0xbc,
	0x90, 0xb8, 0xd5, 0xa7, 0xec, 0x23, 0xab, 0xb6, 0x3c, 0xff, 0xa3, 0xe9, 0x01, 0x83, 0x21, 0x49,
	0x91, 0x85, 0x50, 0x41, 0x2f, 0x9b, 0x73, 0x24, 0x52, 0xb4, 0x83, 0xa9, 0x75, 0xbf, 0x04, 0x12,
	0xa9, 0xf6, 0xd1, 0xd4, 0xfa, 0x3e, 0x95, 0x7d, 0xf7, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a,
	0xf7, 0x5a, 0x29, 0xb0, 0x00, 0x00, 0x00,
}
